apiVersion: v1
kind: Template
metadata:
  name: launchpad-builder
  annotations:
    description: This template creates a Build Configuration using an S2I builder.
    tags: instant-app
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    description: The branch name for the application
    displayName: Source Branch
    value: master
    required: true
  - name: SOURCE_REPOSITORY_DIR
    description: The location within the source repo of the application
    displayName: Source Directory
    value: .
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook.
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: nodejs-rest-http-crud-redhat
    spec: {}
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: runtime
    spec:
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: 'registry.access.redhat.com/rhoar-nodejs/nodejs-10:latest'
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: nodejs-rest-http-crud-redhat
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'nodejs-rest-http-crud-redhat:latest'
      postCommit: {}
      resources: {}
      source:
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
          ref: '${SOURCE_REPOSITORY_REF}'
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'runtime:latest'
          incremental: true
      triggers:
        - github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
          type: GitHub
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    status:
      lastVersion: 0
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      type: ClusterIP
      selector:
        project: nodejs-rest-http-crud-redhat
        provider: nodeshift
    metadata:
      name: nodejs-rest-http-crud-redhat
      labels:
        provider: nodeshift
        expose: 'true'
        project: nodejs-rest-http-crud-redhat
        version: 2.0.0
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: nodejs-rest-http-crud-redhat
      labels:
        app: nodejs-rest-http-crud-redhat
        provider: nodeshift
        project: nodejs-rest-http-crud-redhat
        version: 2.0.0
    spec:
      template:
        spec:
          containers:
            - env:
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: my-database-secret
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: my-database-secret
                      key: password
              readinessProbe:
                httpGet:
                  path: /api/health/readiness
                  port: 8080
                  scheme: HTTP
                failureThreshold: 3
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                httpGet:
                  path: /api/health/liveness
                  port: 8080
                  scheme: HTTP
                failureThreshold: 2
                initialDelaySeconds: 60
                periodSeconds: 3
                successThreshold: 1
                timeoutSeconds: 1
              image: nodejs-rest-http-crud-redhat
              name: nodejs-rest-http-crud-redhat
              securityContext:
                privileged: false
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
        metadata:
          labels:
            app: nodejs-rest-http-crud-redhat
            project: nodejs-rest-http-crud-redhat
            provider: nodeshift
            version: 2.0.0
      replicas: 1
      selector:
        app: nodejs-rest-http-crud-redhat
        project: nodejs-rest-http-crud-redhat
        provider: nodeshift
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - nodejs-rest-http-crud-redhat
            from:
              kind: ImageStreamTag
              name: 'nodejs-rest-http-crud-redhat:latest'
  - apiVersion: v1
    kind: Route
    spec:
      to:
        kind: Service
        name: nodejs-rest-http-crud-redhat
      port:
        targetPort: 8080
    metadata:
      name: nodejs-rest-http-crud-redhat
      labels:
        provider: nodeshift
        project: nodejs-rest-http-crud-redhat
        version: 2.0.0
  - apiVersion: v1
    kind: Secret
    metadata:
      name: my-database-secret
      labels:
        provider: nodeshift
        app: nodejs-rest-http-crud-redhat
        version: 2.0.0
    stringData:
      user: luke
      password: secret
